# Workflow de Integração Contínua focado em execução de testes unitários
# Estrutura preparada para expansão futura (novos jobs, stages, etc.)

name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  # Versão do Node utilizada em todo o workflow
  NODE_VERSION: "24"
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_SCOPE: viniviotis-projects

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      # 2. Configura o ambiente Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3. Habilita o Corepack para gerenciamento do Yarn
      - name: Enable Corepack
        run: corepack enable

      # 4. Instala as dependências do projeto
      - name: Install dependencies
        run: yarn install

      # 5. Executa os testes unitários com Vitest
      - name: Run unit tests
        run: yarn test

  build-and-deploy:
    name: Build & Deploy Vercel Preview
    needs: [ unit-tests ]
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.deploy.outputs.deployment-url }}

    steps:
      # 1. Faz checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      # 2. Configura o ambiente Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3. Habilita o Corepack para gerenciamento do Yarn
      - name: Enable Corepack
        run: corepack enable

      # 4. Instala as dependências do projeto
      - name: Install dependencies
        run: yarn install

      # 5. Obter as configurações do vercel
      - name: Pull Vercel Config
        run: |
          yarn vercel pull --yes \
          --environment=preview \
          --token=$VERCEL_TOKEN \
          --scope=$VERCEL_SCOPE

      # 6. Build para o Vercel
      - name: Build Vercel
        run: yarn vercel build --token=$VERCEL_TOKEN

      # 7. Deploy preview no vercel
      - name: Deploy preview
        id: deploy
        run: |
          # O comando 'vercel deploy' com --json é a forma mais segura de pegar a URL
          DEPLOY_URL=$(npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --scope=viniviotis-projects)
          echo "Vercel Preview URL is: $DEPLOY_URL"
          echo "deployment-url=$DEPLOY_URL" >> $GITHUB_OUTPUT

  e2e-tests:
    name: Run E2E Tests
    needs: [ build-and-deploy ]
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      # 2. Configura o ambiente Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Log BASE_URL
        run: |
          echo "The E2E tests will run against: ${{ needs.build-and-deploy.outputs.deployment-url }}"

      # 3. Habilita o Corepack para gerenciamento do Yarn
      - name: Enable Corepack
        run: corepack enable

      # 4. Instala as dependências do projeto
      - name: Install dependencies
        run: yarn install

      # 5. Instalação do Chromium
      - name: Install Plawright Browser
        run: yarn playwright install --with-deps chromium

      # 6. Execução dos Testes de Regressão
      - name: Run E2E Regression Tests
        run: yarn playwright test
        env:
          BASE_URL: ${{ needs.build-and-deploy.outputs.deployment-url }}
          DATABASE_URL: ${{ secrets.PREVIEW_DATABASE_URL }}

      # 7. Relatório de Testes Automatizados
      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7.0.1
        with:
          name: playwright-report
          path: playwright-report

      # 8. Publicar report JSON do TestDino
      - name: Publish Testdino Report
        if: ${{ !cancelled() }}
        run: npx tdpw upload ./playwright-report --token=${{ secrets.TD_TOKEN }}

  promote:
    name: Promote to Production
    needs: [ build-and-deploy, e2e-tests ]
    runs-on: ubuntu-latest

    steps:
      # 1. Faz checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      # 2. Configura o ambiente Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # 3. Habilita o Corepack para gerenciamento do Yarn
      - name: Enable Corepack
        run: corepack enable

      # 4. Instala as dependências do projeto
      - name: Install dependencies
        run: yarn install

      # 5. Obter as configurações do vercel (Produção)
      - name: Pull Vercel Config (Production)
        run: |
          yarn vercel pull --yes \
          --environment=production \
          --token=$VERCEL_TOKEN \
          --scope=$VERCEL_SCOPE

      # 6. Build para o Vercel (Produção)
      - name: Build Vercel (Production)
        run: yarn vercel build --prod --token=$VERCEL_TOKEN

      # 7. Deploy Vercel (Produção)
      - name: Deploy Vercel (Production)
        run: |
          yarn vercel deploy --prebuilt --prod \
          --token=$VERCEL_TOKEN \
          --scope=$VERCEL_SCOPE
